### ISSUE TITLE
Search on front page does not copy over the search term to the search page (react-based search)

### ISSUE THREAD

**Issue by tisto** [collective/collective.solr#187]
1) Go to front page
2) type search term into search field
3) click the search button
4) redirect to "@search" view
-> search field in the header shows the search term
-> search field in the content view does not show the search term

expected result:
-> both search fields show the search term

**Comment by sneridagh** [comment]
After one year of JS tooling evolution I would like to update and refactor the whole thing a bit :) Hoewever, the bug is fixed now.

We still have to integrate properly the widget on Plone4, now it's broken because of the interaction with jquery.tools and livesearch, so tests can't pass without fixing that too.
