### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by tisto** [collective/collective.solr#210]
- [x] Fix failing tests on no-collective-indexing PR: https://github.com/collective/collective.solr/pull/206
- [x] Make collective.indexing dependency optional (needs to be discussed)
- [x] Plone 5.2 compatibility (fix failing tests, make sure everything works)
- [x] Make sure we do not depend on Archetypes in any way
- [x] Add Python 3 compatibility

Any takers? :)

I'd be more than happy to help. Though, most likely I won't have much time to do it myself right now.

**Comment by zopyx** [comment]
What is the story with dependency on Archetypes.CatalogMultiplex?

**Comment by tisto** [comment]
@zopyx will look into it. That was just added with the latest a2. My fault...

**Comment by gforcada** [comment]
On `events.py` there are also references to archetypes... https://github.com/collective/collective.solr/blob/61e72600bab3f01617fdca9cc090896262d389bc/src/collective/solr/events.py#L6

**Comment by jnns** [comment]
During the Plone Tagung sprint in Munich I started work on porting to Python 3 but have since not managed to work on it futher. 

The dependency on `collective.indexing` is also blocking Python 3 support but @tisto stated on [this pull request](https://github.com/collective/collective.solr/pull/206) that it shouldn't be completely removed to not break support for Plone 4.3. So I based my work on @gforcada 's branch but instead of removing it completely, I made `collective.indexing` optional. 

I probably won't be able to work on it in the foreseeable future but maybe some of it can be of use to any of you:
https://github.com/derFreitag/collective.solr/tree/python3

Thanks

**Comment by tisto** [comment]
@gforcada @jnns @zopyx I created a more detailed roadmap to Plone 5.2 and Python 3. Please have a look and let me know what you think. We have to discuss, if we want to keep compatibility for old Plone versions (something I am in favor of) or cut a new Plone 5.2 / Python 3 only release.

**Comment by reinhardt** [comment]
Any objections to merging the work from derFreitag and syslabcom to the python3 branch here in the collective as @pilz suggested on twitter? I think it's a good idea to have a common base and I can't see it doing any damage (the current python3 branch looks empty).

https://github.com/derFreitag/collective.solr/tree/python3
https://github.com/syslabcom/collective.solr/tree/python3

**Comment by pilz** [comment]
I would say, in the absence of further comments, just do it. The branch is quickly renamed if someone has an objection. Go for it!

**Comment by gforcada** [comment]
@reinhardt as I mentioned on another pull request/issue: as for the commits on derFreitag, feel free to grab them and do whatever you see best with them :+1: if we didn't push that upstream first is due to the amount of patches that are yet to be accepted upstream  :confused:

**Comment by reinhardt** [comment]
FTR, #229 is green on travis. Reviews appreciated.

**Comment by tisto** [comment]
First alpha release is out: https://pypi.org/project/collective.solr/8.0.0a1/ 

Thank you @reinhardt @jnns @csenger for your help!!!
