### ISSUE TITLE
Getting started howto.

### ISSUE THREAD

**Issue by tisto** [collective/collective.solr#49]
Write a document about how to get started with c.solr and c.r.solrinstance.

**Comment by loechel** [comment]
We should have a decent documentation for Plone and Solr. The Question is where that should life. docs.plone.org would be the best place, there is the general documentation that could link to the specific documentations of c.solr and c.r.solrinstance.

We should create a sphinx documentation in c.solr and reference a sphinx documentation in c.r.solrinstance on Solr setup specifics and which fields needs to be used and why to be connected with Plone.

Any thoughts on document structure or that from @saily @svx

**Comment by svx** [comment]
Add the docs /docs of the collective.solr, then we will link to these docs. If collective.solr is moving to core we we include the docs like we do it for plone.api and other projects. :)

**Comment by pilz** [comment]
Looking at collective.recipe.solrinstance, the documentation there is structured by configuration parameter. This is handy for a quick lookup when the integrator needs to know the syntax. To me it also feels right to find it there.

Looking at collective.solr on pypi, the documentation is about 2 years old and tries to cover the whole ground of solr in plone and touches everything a bit. There is even a paragraph on elevation without using solr's elevation feature and there are features that only work with archetypes. It seems to need a refresh or a validation.

On docs.plone.org I don't see anything on solr, not even a pointer to the packages. To me it seems that would be the optimal place to get started and to have documentation on what could be good practice in using solr with plone. Then eventually linking to the package docs for further details.

Or of course we put all of this into collective.solr (after all it is very much meant for plone only), update this documentation and structure it in a way so that it can be linked by docs.plone.org.

The last option would be my preference. However I think there must be a starting point within docs.plone.org pointing there in a controlled way.

**Comment by tisto** [comment]
+1 on creating sphinx-based c.solr docs (from the scratch) that is fetched into docs.plone.org. We can take stuff from the old c.solr docs if it makes sense. 

c.r.solrinstance is used outside the Plone community and already has a sufficient documentation in my option.

On docs.plone.org we should have a starting point/short intro about the possible options (c.solr, alm.solrindex, elasticsearch).

**Comment by loechel** [comment]
@svx, any suggestion for a starting page in docs.plone.org? I would see a start page in both sections: 

* http://docs.plone.org/adapt-and-extend/index.html Adapting & Extending Plone
* http://docs.plone.org/manage/index.html Installing, Managing and Updating Plone

could you set something up in the structure and point us to that, please.

The documentation should live in the add-on package as long as the life outsite of the core.

**Comment by svx** [comment]
@loechel the idea is that we have the docs always in the repository of the package it does not matter if it's core or collective, further setup is, that we fetch the docs from the repo and include it into docs.plone.org, like we do it already for certrain packages, the difference between core and collective is, that we include docs from core packages and link to collective packages, this approach is 'newish'.

The whole idea is, that is would be easier to keep the docs up2date, because we wo not have to change them on different locations.

So for now we do not have to setup something, if I get a 'good to go' I will link them from both locations, for now, if solr is moving to core, I will change the link to a include the docs and make a reference.

**Comment by tomgross** [comment]
This is now covered in the Plone training https://github.com/plone/training/tree/master/solr-training.
Please contribute there.
